### ISSUE TITLE
`uses:` keyword is not currently supported

### ISSUE THREAD

**Issue by mayong43111** [Azure/data-factory-deploy-action#3]
I have a workflow like this:

```
        - name: Login via Az module
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            enable-AzPSSession: true
            
        - name: publish ADF resource
          uses: Azure/data-factory-deploy-action@v1.1.0
          with:
            resourceGroupName: Dev-DataOps-BigData
            dataFactoryName: poc-dataops-adf-etl-cn2
            armTemplateFile: ./dev-dataops-adf-etl-cn2/ARMTemplateForFactory.json
            armTemplateParametersFile: ./dev-dataops-adf-etl-cn2/ARMTemplateParametersForFactory_POC_CN2.json
```
but an error has occurred and  the message is : `uses:` keyword is not currently supported.
and log is 
```
Current runner version: '2.284.0'
Runner name: 'runner01'
Runner group name: 'Default'
Machine name: 'ghe-runn'
GITHUB_TOKEN Permissions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' (SHA:5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f)
Download action repository 'azure/login@v1' (SHA:89d153571fe9a34ed70fcf9f1d95ab8debea7a73)
Download action repository 'Azure/data-factory-deploy-action@v1.1.0' (SHA:27ee1c6cf0cd5ce53452afccfa7f634bece1c61a)
Error: `uses:` keyword is not currently supported.

```
Such as log can be seen ,my runner version is 2.284. 

thank a lot
